branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2
dist: precise
env:
- RUN_INTEGRATION_TESTS=true
- RUN_INTEGRATION_TESTS=false
install:
- ./.travis_install.sh
jdk:
- oraclejdk8
language: java
matrix:
  exclude:
  - env: RUN_INTEGRATION_TESTS=false
    jdk: openjdk7
  - env: RUN_INTEGRATION_TESTS=false
    jdk: oraclejdk8
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- ./.travis_test.sh
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
sudo: false
